spring:
  profiles:
    active: postgres
  application:
    name: regions-nuts-importer
  datasource:  
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:nuts_importer
    username: sa
    password: 
    hikari:
      maximum-pool-size: 5
    platform: h2
  h2:
    console:
      enabled: true
  batch:
    job:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    properties: 
      hibernate:
        dialect: org.hibernate.spatial.dialect.h2geodb.GeoDBDialect
    show-sql: false

app:
  nuts:
    data-dir: classpath:data/shapefiles
  geonames:
    data-dir: file://D:/Temp/GeoNames
    postal-code-data-dir: file://D:/Temp/GeoNames/PostalCodes
